
networks:
  proxy-net:
    name: proxy-net
    driver: bridge

include:
  - npm/docker-compose.yml
  - ddns/docker-compose.yml
  - portainer/docker-compose.yml
  - uptimekuma/docker-compose.yml
  - memos/docker-compose.yml