
networks:
  proxy-net:
    external: true

include:
  - npm/docker-compose.yml
  - ddns/docker-compose.yml
  - portainer/docker-compose.yml
  - uptimekuma/docker-compose.yml
  - memos/docker-compose.yml
  - nextcloud/docker-compose.yml