services:
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    restart: unless-stopped
    
    environment:
      - PUID=1000  # (Rocky Linux의 neoskyclad 계정 ID)
      - PGID=1000  # (Rocky Linux의 neoskyclad 계정 ID)
      - TZ=Asia/Seoul
      - SUBDOMAINS=neoskyclad  # ('.duckdns.org' 앞부분만)
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=true # 로그를 남김
      
    volumes:
      - ./config:/config